/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package countme;

import Audio.Sound;
import javax.swing.ImageIcon;

/**
 *
 * @author Huawei
 */
public class CountMe extends javax.swing.JFrame {

    /**
     * Creates new form CountMe
     */
    public CountMe() {
        initComponents();
        
        sound = new Sound();
        sound.soundMusic();
        ImageIcon img = new ImageIcon("C:\\Programming\\Java\\CountMe\\CountMe_icon.png");
        this.setIconImage(img.getImage());
    }
    
    //GAME SOUND
    private static Sound sound;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        tutorial_btn = new javax.swing.JButton();
        quit_btn = new javax.swing.JButton();
        play_btn = new javax.swing.JButton();
        music_btn = new javax.swing.JToggleButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        tutorial = new javax.swing.JPanel();
        okay_btn = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        tagline = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        text_bg = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        difficulty = new javax.swing.JPanel();
        easy_btn1 = new javax.swing.JButton();
        moderate_btn1 = new javax.swing.JButton();
        hard_btn1 = new javax.swing.JButton();
        menu_btn1 = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        easy_panel = new javax.swing.JPanel();
        okay_easy = new javax.swing.JButton();
        description1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        text_bg1 = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();
        medium_panel = new javax.swing.JPanel();
        okay_medium = new javax.swing.JButton();
        description2 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        text_bg2 = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();
        hard_panel = new javax.swing.JPanel();
        okay_hard = new javax.swing.JButton();
        description3 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        tagline1 = new javax.swing.JLabel();
        text_bg3 = new javax.swing.JLabel();
        background7 = new javax.swing.JLabel();
        quit_panel = new javax.swing.JPanel();
        confirm_label_1 = new javax.swing.JLabel();
        no_btn = new javax.swing.JButton();
        yes_btn = new javax.swing.JButton();
        confirm_label_2 = new javax.swing.JLabel();
        txt_bg = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setTitle("Count Me");
        setBackground(new java.awt.Color(86, 45, 128));
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setFocusable(false);
        setFocusableWindowState(false);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(800, 625));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 625));

        home.setPreferredSize(new java.awt.Dimension(800, 600));
        home.setLayout(null);

        tutorial_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_btn.png"))); // NOI18N
        tutorial_btn.setBorder(null);
        tutorial_btn.setContentAreaFilled(false);
        tutorial_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_btn_pressed.png"))); // NOI18N
        tutorial_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_btn_hover.png"))); // NOI18N
        tutorial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial_btnActionPerformed(evt);
            }
        });
        home.add(tutorial_btn);
        tutorial_btn.setBounds(620, 20, 80, 70);

        quit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/quit_btn.png"))); // NOI18N
        quit_btn.setBorder(null);
        quit_btn.setContentAreaFilled(false);
        quit_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/quit_btn_pressed.png"))); // NOI18N
        quit_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/quit_btn_hover.png"))); // NOI18N
        quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btnActionPerformed(evt);
            }
        });
        home.add(quit_btn);
        quit_btn.setBounds(290, 460, 210, 90);

        play_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/play_btn.png"))); // NOI18N
        play_btn.setBorder(null);
        play_btn.setBorderPainted(false);
        play_btn.setContentAreaFilled(false);
        play_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        play_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        play_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/play_btn_pressed (2).png"))); // NOI18N
        play_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/play_btn_pressed.png"))); // NOI18N
        play_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_btnActionPerformed(evt);
            }
        });
        home.add(play_btn);
        play_btn.setBounds(290, 350, 210, 90);

        music_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/music_btn.png"))); // NOI18N
        music_btn.setBorder(null);
        music_btn.setContentAreaFilled(false);
        music_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/music_btn_hover.png"))); // NOI18N
        music_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_music.png"))); // NOI18N
        music_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                music_btnActionPerformed(evt);
            }
        });
        home.add(music_btn);
        music_btn.setBounds(700, 20, 70, 70);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/logo (2).png"))); // NOI18N
        home.add(logo);
        logo.setBounds(0, 90, 800, 230);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.setRequestFocusEnabled(false);
        background.setVerifyInputWhenFocusTarget(false);
        home.add(background);
        background.setBounds(0, 0, 800, 600);

        tutorial.setPreferredSize(new java.awt.Dimension(800, 625));
        tutorial.setLayout(null);

        okay_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn.png"))); // NOI18N
        okay_btn.setBorder(null);
        okay_btn.setContentAreaFilled(false);
        okay_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn_pressed.png"))); // NOI18N
        okay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_btnActionPerformed(evt);
            }
        });
        tutorial.add(okay_btn);
        okay_btn.setBounds(340, 480, 120, 46);

        description.setFont(new java.awt.Font("Mochiy Pop One", 0, 15)); // NOI18N
        description.setForeground(new java.awt.Color(157, 229, 248));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("<html>\nObjective: Your mission is to solve counting puzzles to advance in the game. Each puzzle presents a unique scenario or arrangement of objects, and your task is to accurately count them to find the correct answer.\n<br><br>\nGameplay: Carefully examine each question presented on the screen. Then, use your counting skills to determine the total number of items requested. Once you've counted them, enter your answer.\n<br><br>\nHint System: Stuck on a puzzle? Use your coins to access hints that can provide helpful clues. Earn coins by correctly solving puzzles – the more you solve, the more hints you'll have at your disposal!\n<html>\n\n");
        tutorial.add(description);
        description.setBounds(100, 160, 620, 300);

        tagline.setFont(new java.awt.Font("Mochiy Pop One", 0, 18)); // NOI18N
        tagline.setForeground(new java.awt.Color(157, 229, 248));
        tagline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagline.setText(" The best game for honing your logical skills!");
        tutorial.add(tagline);
        tagline.setBounds(80, 120, 650, 40);

        title.setFont(new java.awt.Font("Modak", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(157, 229, 248));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Welcome to CountMe!");
        tutorial.add(title);
        title.setBounds(80, 70, 650, 70);

        text_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_bg.png"))); // NOI18N
        tutorial.add(text_bg);
        text_bg.setBounds(50, 20, 720, 550);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background2.setRequestFocusEnabled(false);
        background2.setVerifyInputWhenFocusTarget(false);
        tutorial.add(background2);
        background2.setBounds(0, 0, 800, 600);

        difficulty.setPreferredSize(new java.awt.Dimension(800, 625));
        difficulty.setLayout(null);

        easy_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn.png"))); // NOI18N
        easy_btn1.setBorder(null);
        easy_btn1.setContentAreaFilled(false);
        easy_btn1.setEnabled(false);
        easy_btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn_p.png"))); // NOI18N
        easy_btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn_h.png"))); // NOI18N
        easy_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easy_btn1ActionPerformed(evt);
            }
        });
        difficulty.add(easy_btn1);
        easy_btn1.setBounds(270, 110, 290, 130);

        moderate_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn.png"))); // NOI18N
        moderate_btn1.setBorder(null);
        moderate_btn1.setContentAreaFilled(false);
        moderate_btn1.setEnabled(false);
        moderate_btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn_p.png"))); // NOI18N
        moderate_btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn_h.png"))); // NOI18N
        moderate_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moderate_btn1ActionPerformed(evt);
            }
        });
        difficulty.add(moderate_btn1);
        moderate_btn1.setBounds(270, 250, 290, 120);

        hard_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn.png"))); // NOI18N
        hard_btn1.setBorder(null);
        hard_btn1.setContentAreaFilled(false);
        hard_btn1.setEnabled(false);
        hard_btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn_p.png"))); // NOI18N
        hard_btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn_h.png"))); // NOI18N
        hard_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard_btn1ActionPerformed(evt);
            }
        });
        difficulty.add(hard_btn1);
        hard_btn1.setBounds(270, 380, 280, 120);

        menu_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu.png"))); // NOI18N
        menu_btn1.setBorder(null);
        menu_btn1.setContentAreaFilled(false);
        menu_btn1.setEnabled(false);
        menu_btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu_p.png"))); // NOI18N
        menu_btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu_h.png"))); // NOI18N
        menu_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_btn1ActionPerformed(evt);
            }
        });
        difficulty.add(menu_btn1);
        menu_btn1.setBounds(10, 530, 120, 50);

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background4.setRequestFocusEnabled(false);
        background4.setVerifyInputWhenFocusTarget(false);
        difficulty.add(background4);
        background4.setBounds(0, 0, 800, 600);

        easy_panel.setPreferredSize(new java.awt.Dimension(800, 625));
        easy_panel.setLayout(null);

        okay_easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn.png"))); // NOI18N
        okay_easy.setBorder(null);
        okay_easy.setContentAreaFilled(false);
        okay_easy.setEnabled(false);
        okay_easy.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn_pressed.png"))); // NOI18N
        okay_easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_easyActionPerformed(evt);
            }
        });
        easy_panel.add(okay_easy);
        okay_easy.setBounds(340, 450, 120, 46);

        description1.setFont(new java.awt.Font("Mochiy Pop One", 0, 18)); // NOI18N
        description1.setForeground(new java.awt.Color(157, 229, 248));
        description1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description1.setText("<html>• The easy round consists of 15 questions. <br> <br> • You have three lives to answer with 30 seconds timer.<br> <br> \n• Each correct answers will grant you 2 coins. <br>You may use these coins to buy hints. (10 coints each hint)<html>");
        easy_panel.add(description1);
        description1.setBounds(80, 170, 650, 190);

        title1.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        title1.setForeground(new java.awt.Color(157, 229, 248));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Easy Round");
        easy_panel.add(title1);
        title1.setBounds(80, 70, 650, 100);

        text_bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_bg.png"))); // NOI18N
        easy_panel.add(text_bg1);
        text_bg1.setBounds(50, 20, 720, 550);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background5.setRequestFocusEnabled(false);
        background5.setVerifyInputWhenFocusTarget(false);
        easy_panel.add(background5);
        background5.setBounds(0, 0, 800, 600);

        medium_panel.setPreferredSize(new java.awt.Dimension(800, 625));
        medium_panel.setLayout(null);

        okay_medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn.png"))); // NOI18N
        okay_medium.setBorder(null);
        okay_medium.setContentAreaFilled(false);
        okay_medium.setEnabled(false);
        okay_medium.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn_pressed.png"))); // NOI18N
        okay_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_mediumActionPerformed(evt);
            }
        });
        medium_panel.add(okay_medium);
        okay_medium.setBounds(340, 450, 120, 46);

        description2.setFont(new java.awt.Font("Mochiy Pop One", 0, 18)); // NOI18N
        description2.setForeground(new java.awt.Color(157, 229, 248));
        description2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description2.setText("<html>• This round consists of 20 questions. <br> <br> • You have two lives to answer with 45 seconds timer.<br> <br>  • Each correct answers will grant you 5 coins. <br>You may use these coins to buy hints. (10 coints each hint)<html>");
        medium_panel.add(description2);
        description2.setBounds(80, 170, 650, 190);

        title2.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        title2.setForeground(new java.awt.Color(157, 229, 248));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Medium Round");
        medium_panel.add(title2);
        title2.setBounds(80, 70, 650, 100);

        text_bg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_bg.png"))); // NOI18N
        medium_panel.add(text_bg2);
        text_bg2.setBounds(50, 20, 720, 550);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background6.setRequestFocusEnabled(false);
        background6.setVerifyInputWhenFocusTarget(false);
        medium_panel.add(background6);
        background6.setBounds(0, 0, 800, 600);

        hard_panel.setPreferredSize(new java.awt.Dimension(800, 625));
        hard_panel.setLayout(null);

        okay_hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn.png"))); // NOI18N
        okay_hard.setBorder(null);
        okay_hard.setContentAreaFilled(false);
        okay_hard.setEnabled(false);
        okay_hard.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/okay_btn_pressed.png"))); // NOI18N
        okay_hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_hardActionPerformed(evt);
            }
        });
        hard_panel.add(okay_hard);
        okay_hard.setBounds(340, 460, 120, 46);

        description3.setFont(new java.awt.Font("Mochiy Pop One", 0, 16)); // NOI18N
        description3.setForeground(new java.awt.Color(157, 229, 248));
        description3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description3.setText("<html> • In this round, you'll encounter fill-in-the-blank questions. <br> <br> • Your answers should be provided using numbers only, without any commas or spacing. <br> <br> \n• This round consists of 25 questions.  <br> <br>  • You only  have one life to answer with 60 seconds timer. <br> <br>   • Each correct answers will grant you 10 coins. <br>You may use these coins to buy hints. (10 coints each hint)<html>");
        hard_panel.add(description3);
        description3.setBounds(100, 170, 630, 270);

        title3.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        title3.setForeground(new java.awt.Color(157, 229, 248));
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Hard Round");
        hard_panel.add(title3);
        title3.setBounds(80, 60, 650, 90);

        tagline1.setFont(new java.awt.Font("Mochiy Pop One", 0, 18)); // NOI18N
        tagline1.setForeground(new java.awt.Color(157, 229, 248));
        tagline1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagline1.setText("READ FIRST.");
        hard_panel.add(tagline1);
        tagline1.setBounds(80, 120, 650, 50);

        text_bg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/tutorial_bg.png"))); // NOI18N
        hard_panel.add(text_bg3);
        text_bg3.setBounds(50, 20, 720, 550);

        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background7.setRequestFocusEnabled(false);
        background7.setVerifyInputWhenFocusTarget(false);
        hard_panel.add(background7);
        background7.setBounds(0, 0, 800, 600);

        quit_panel.setPreferredSize(new java.awt.Dimension(800, 625));
        quit_panel.setLayout(null);

        confirm_label_1.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        confirm_label_1.setForeground(new java.awt.Color(157, 229, 248));
        confirm_label_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirm_label_1.setText("Do you want to");
        confirm_label_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(confirm_label_1);
        confirm_label_1.setBounds(150, 200, 500, 60);

        no_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn.png"))); // NOI18N
        no_btn.setBorder(null);
        no_btn.setContentAreaFilled(false);
        no_btn.setEnabled(false);
        no_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn_p.png"))); // NOI18N
        no_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn_h.png"))); // NOI18N
        no_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_btnActionPerformed(evt);
            }
        });
        quit_panel.add(no_btn);
        no_btn.setBounds(410, 360, 170, 70);

        yes_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn.png"))); // NOI18N
        yes_btn.setBorder(null);
        yes_btn.setContentAreaFilled(false);
        yes_btn.setEnabled(false);
        yes_btn.setFocusable(false);
        yes_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn_p.png"))); // NOI18N
        yes_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn_h.png"))); // NOI18N
        yes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_btnActionPerformed(evt);
            }
        });
        quit_panel.add(yes_btn);
        yes_btn.setBounds(210, 360, 170, 70);

        confirm_label_2.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        confirm_label_2.setForeground(new java.awt.Color(157, 229, 248));
        confirm_label_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirm_label_2.setText("quit?");
        confirm_label_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(confirm_label_2);
        confirm_label_2.setBounds(150, 260, 500, 60);

        txt_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/txt_bg.png"))); // NOI18N
        txt_bg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(txt_bg);
        txt_bg.setBounds(150, 120, 520, 410);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background3.setRequestFocusEnabled(false);
        background3.setVerifyInputWhenFocusTarget(false);
        quit_panel.add(background3);
        background3.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(quit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(easy_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(medium_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hard_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(quit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(easy_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(medium_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hard_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_btnActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        
        easy_btn1.setEnabled(true);
        moderate_btn1.setEnabled(true);
        hard_btn1.setEnabled(true);
        menu_btn1.setEnabled(true);
        
        tutorial.setVisible(false);
        quit_panel.setVisible(false);
        home.setVisible(false);
        difficulty.setVisible(true);
        
    }//GEN-LAST:event_play_btnActionPerformed

    private void tutorial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial_btnActionPerformed
        // TODO add your handling code here:
        tutorial.setVisible(true);
        home.setVisible(false);
        sound.soundClick(isMuted);
    }//GEN-LAST:event_tutorial_btnActionPerformed

    private void quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btnActionPerformed
        // TODO add your handling code her
        no_btn.setEnabled(true);
        yes_btn.setEnabled(true);
        home.setVisible(false);
        tutorial.setVisible(false);
        quit_panel.setVisible(true);
        sound.soundClick(isMuted);
        
    }//GEN-LAST:event_quit_btnActionPerformed

    private void okay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_btnActionPerformed
        // TODO add your handling code here
        home.setVisible(true);
        tutorial.setVisible(false);
        sound.soundClick(isMuted);
        
    }//GEN-LAST:event_okay_btnActionPerformed

    private void no_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_btnActionPerformed
        // TODO add your handling code here:
        no_btn.setEnabled(false);
        yes_btn.setEnabled(false);
        home.setVisible(true);
        quit_panel.setVisible(false);
        sound.soundClick(isMuted);
    }//GEN-LAST:event_no_btnActionPerformed

    private void yes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_btnActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        System.exit(0);
        
    }//GEN-LAST:event_yes_btnActionPerformed

    private void easy_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easy_btn1ActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        okay_easy.setEnabled(true);
        easy_panel.setVisible(true);
        difficulty.setVisible(false);
    }//GEN-LAST:event_easy_btn1ActionPerformed

    private void moderate_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moderate_btn1ActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        okay_medium.setEnabled(true);
        medium_panel.setVisible(true);
        easy_panel.setVisible(false);
        difficulty.setVisible(false);                                  
    }//GEN-LAST:event_moderate_btn1ActionPerformed

    private void hard_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard_btn1ActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        okay_hard.setEnabled(true);
        medium_panel.setVisible(false);
        easy_panel.setVisible(false);
        difficulty.setVisible(false); 
        hard_panel.setVisible(true);
    }//GEN-LAST:event_hard_btn1ActionPerformed

    private void menu_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_btn1ActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        easy_btn1.setEnabled(false);
        moderate_btn1.setEnabled(false);
        hard_btn1.setEnabled(false);
        menu_btn1.setEnabled(false);
        tutorial.setVisible(false);
        tutorial.setVisible(false);
        quit_panel.setVisible(false);
        difficulty.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_menu_btn1ActionPerformed

    public boolean isPlaying = true;
    public boolean isMuted = false;
            
    private void music_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_music_btnActionPerformed
        // TODO add your handling code here:
        if (isPlaying) {
            sound.pauseMusic();
            isPlaying = false;
            isMuted = true;
        } else {
            sound.resumeMusic();
            isPlaying = true;
            isMuted = false;
        }
        
        sound.soundClick(isMuted);
    }//GEN-LAST:event_music_btnActionPerformed

    private void okay_easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_easyActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        sound.endMusic();
        dispose();
        new Easy().setVisible(true);
    }//GEN-LAST:event_okay_easyActionPerformed

    private void okay_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_mediumActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        sound.endMusic();
        dispose();
        new Medium().setVisible(true);
    }//GEN-LAST:event_okay_mediumActionPerformed

    private void okay_hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_hardActionPerformed
        // TODO add your handling code here:
        sound.soundClick(isMuted);
        sound.endMusic();
        dispose();
        new Hard().setVisible(true);
    }//GEN-LAST:event_okay_hardActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JLabel confirm_label_1;
    private javax.swing.JLabel confirm_label_2;
    private javax.swing.JLabel description;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel description3;
    private javax.swing.JPanel difficulty;
    private javax.swing.JButton easy_btn1;
    private javax.swing.JPanel easy_panel;
    private javax.swing.JButton hard_btn1;
    private javax.swing.JPanel hard_panel;
    private javax.swing.JPanel home;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel medium_panel;
    private javax.swing.JButton menu_btn1;
    private javax.swing.JButton moderate_btn1;
    private javax.swing.JToggleButton music_btn;
    private javax.swing.JButton no_btn;
    private javax.swing.JButton okay_btn;
    private javax.swing.JButton okay_easy;
    private javax.swing.JButton okay_hard;
    private javax.swing.JButton okay_medium;
    private javax.swing.JButton play_btn;
    private javax.swing.JButton quit_btn;
    private javax.swing.JPanel quit_panel;
    private javax.swing.JLabel tagline;
    private javax.swing.JLabel tagline1;
    private javax.swing.JLabel text_bg;
    private javax.swing.JLabel text_bg1;
    private javax.swing.JLabel text_bg2;
    private javax.swing.JLabel text_bg3;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JPanel tutorial;
    private javax.swing.JButton tutorial_btn;
    private javax.swing.JLabel txt_bg;
    private javax.swing.JButton yes_btn;
    // End of variables declaration//GEN-END:variables
}
