/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package countme;

/**
 *
 * @author Huawei
 */
public class Difficulty extends javax.swing.JFrame {

    /**
     * Creates new form Difficulty
     */
    public Difficulty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficulty = new javax.swing.JPanel();
        easy_btn = new javax.swing.JButton();
        moderate_btn = new javax.swing.JButton();
        hard_btn = new javax.swing.JButton();
        mebu_btn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        difficulty.setPreferredSize(new java.awt.Dimension(800, 600));
        difficulty.setLayout(null);

        easy_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn.png"))); // NOI18N
        easy_btn.setBorder(null);
        easy_btn.setContentAreaFilled(false);
        easy_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn_p.png"))); // NOI18N
        easy_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/easy_btn_h.png"))); // NOI18N
        easy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easy_btnActionPerformed(evt);
            }
        });
        difficulty.add(easy_btn);
        easy_btn.setBounds(280, 110, 270, 130);

        moderate_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn.png"))); // NOI18N
        moderate_btn.setBorder(null);
        moderate_btn.setContentAreaFilled(false);
        moderate_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn_p.png"))); // NOI18N
        moderate_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/medium_btn_h.png"))); // NOI18N
        moderate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moderate_btnActionPerformed(evt);
            }
        });
        difficulty.add(moderate_btn);
        moderate_btn.setBounds(280, 250, 270, 120);

        hard_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn.png"))); // NOI18N
        hard_btn.setBorder(null);
        hard_btn.setContentAreaFilled(false);
        hard_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn_p.png"))); // NOI18N
        hard_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/hard_btn_h.png"))); // NOI18N
        hard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard_btnActionPerformed(evt);
            }
        });
        difficulty.add(hard_btn);
        hard_btn.setBounds(280, 380, 270, 120);

        mebu_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu.png"))); // NOI18N
        mebu_btn.setBorder(null);
        mebu_btn.setContentAreaFilled(false);
        mebu_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu_p.png"))); // NOI18N
        mebu_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/menu_h.png"))); // NOI18N
        difficulty.add(mebu_btn);
        mebu_btn.setBounds(10, 540, 120, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background.setText("sadsadsad");
        difficulty.add(background);
        background.setBounds(-40, -10, 801, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 39, Short.MAX_VALUE)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easy_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easy_btnActionPerformed

    private void moderate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moderate_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moderate_btnActionPerformed

    private void hard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Difficulty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel difficulty;
    private javax.swing.JButton easy_btn;
    private javax.swing.JButton hard_btn;
    private javax.swing.JButton mebu_btn;
    private javax.swing.JButton moderate_btn;
    // End of variables declaration//GEN-END:variables
}
