/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package countme;

/**
 *
 * @author Huawei
 */
public class quit extends javax.swing.JFrame {

    /**
     * Creates new form quit
     */
    public quit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quit_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        no_btn1 = new javax.swing.JButton();
        yes_btn2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        quit_panel.setPreferredSize(new java.awt.Dimension(800, 600));
        quit_panel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(157, 229, 248));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Do you want to");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(jLabel4);
        jLabel4.setBounds(150, 200, 500, 60);

        no_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn.png"))); // NOI18N
        no_btn1.setBorder(null);
        no_btn1.setContentAreaFilled(false);
        no_btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn_p.png"))); // NOI18N
        no_btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/no_btn_h.png"))); // NOI18N
        no_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_btn1ActionPerformed(evt);
            }
        });
        quit_panel.add(no_btn1);
        no_btn1.setBounds(420, 360, 160, 70);

        yes_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn.png"))); // NOI18N
        yes_btn2.setBorder(null);
        yes_btn2.setContentAreaFilled(false);
        yes_btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn_p.png"))); // NOI18N
        yes_btn2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/yes_btn_h.png"))); // NOI18N
        yes_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_btn2ActionPerformed(evt);
            }
        });
        quit_panel.add(yes_btn2);
        yes_btn2.setBounds(220, 360, 160, 70);

        jLabel5.setFont(new java.awt.Font("Modak", 0, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(157, 229, 248));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("quit?");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(jLabel5);
        jLabel5.setBounds(150, 260, 500, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/txt_bg.png"))); // NOI18N
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quit_panel.add(jLabel6);
        jLabel6.setBounds(0, 70, 700, 480);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background2.setMaximumSize(new java.awt.Dimension(800, 625));
        background2.setMinimumSize(new java.awt.Dimension(800, 625));
        background2.setPreferredSize(new java.awt.Dimension(800, 625));
        background2.setRequestFocusEnabled(false);
        background2.setVerifyInputWhenFocusTarget(false);
        quit_panel.add(background2);
        background2.setBounds(0, 0, 800, 625);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/countme/Images/background.png"))); // NOI18N
        background1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background1.setPreferredSize(new java.awt.Dimension(800, 625));
        background1.setRequestFocusEnabled(false);
        background1.setVerifyInputWhenFocusTarget(false);
        quit_panel.add(background1);
        background1.setBounds(0, 0, 800, 625);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(quit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(quit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void no_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_btn1ActionPerformed
        // TODO add your handling code here:
        CountMe home = new CountMe();
        quit_panel.setVisible(false);
        home.setVisible(true);
        
    }//GEN-LAST:event_no_btn1ActionPerformed

    private void yes_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_btn2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_yes_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton no_btn1;
    private javax.swing.JPanel quit_panel;
    private javax.swing.JButton yes_btn2;
    // End of variables declaration//GEN-END:variables
}
